name: Docker build
on:
  workflow_dispatch:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  schedule:
    - cron: '0 2 * * *'
jobs:
  space_robots:
    runs-on: ubuntu-20.04
    steps:
      - name: "Free up disk space"
        run: |
          sudo apt-get -qq purge "ghc*"
          sudo apt-get clean
          # cleanup docker images not used by us
          docker system prune -af
          # free up a lot of stuff from /usr/local
          sudo rm -rf /usr/local
          df -h
      # - name: Login to ghcr
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      # - name: Checkout
      #   uses: actions/checkout@v2
      # - name: Set up buildx
      #   uses: docker/setup-buildx-action@v1

      #   # 登录到 Docker Hub（或其他 Docker 注册表）
      # - name: Log in to Docker Hub
      #   # 仅在非 PR 事件中执行登录
      #   if: github.event_name != 'pull_request'
      #   # 使用 Docker 登录动作
      #   uses: docker/login-action@v2
      #   with:
      #     # 使用自定义的注册表（默认为 Docker Hub）
      #     registry: ${{ env.REGISTRY }}
      #     # 从 GitHub Secrets 获取 Docker 用户名
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     # 从 GitHub Secrets 获取 Docker 密码
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Build moveit2 image
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: moveit2
      #     push: ${{ github.event_name != 'pull_request' }}
      #     tags: zxfw9931/moveit2:latest
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max
      #     no-cache: false
      #     build-args: |
      #       SPACE_ROS_IMAGE=osrf/space-ros:main
      #     outputs: type=docker,dest=/tmp/moveit2.tar
      # - name: Build space robots demo image
      #   run: |
      #     docker load --input /tmp/moveit2.tar
      #     docker images
      #     cd space_robots && ./build.sh
  space_nav2:
    runs-on: ubuntu-20.04
    steps:

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGES_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up buildx
        uses: docker/setup-buildx-action@v1
      - name: Build space_nav2 image
        uses: docker/build-push-action@v2
        with:
          context: navigation2
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/kaneleo/space_nav2:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          no-cache: false
          build-args: |
            SPACE_ROS_IMAGE=osrf/space-ros:main
